version: "3.9"

services:
  barbershop_db:
    container_name: barbershop_db
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: admin
      
      POSTGRES_DB: barbershop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}